package com.exam.ssm.model;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.AID
     *
     * @mbg.generated Mon May 07 13:22:50 CST 2018
     */
    private int aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.NAME
     *
     * @mbg.generated Mon May 07 13:22:50 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.TEL
     *
     * @mbg.generated Mon May 07 13:22:50 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.PASSWORD
     *
     * @mbg.generated Mon May 07 13:22:50 CST 2018
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.AID
     *
     * @return the value of admin.AID
     *
     * @mbg.generated Mon May 07 13:22:50 CST 2018
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.AID
     *
     * @param aid the value for admin.AID
     *
     * @mbg.generated Mon May 07 13:22:50 CST 2018
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.NAME
     *
     * @return the value of admin.NAME
     *
     * @mbg.generated Mon May 07 13:22:50 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.NAME
     *
     * @param name the value for admin.NAME
     *
     * @mbg.generated Mon May 07 13:22:50 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.TEL
     *
     * @return the value of admin.TEL
     *
     * @mbg.generated Mon May 07 13:22:50 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.TEL
     *
     * @param tel the value for admin.TEL
     *
     * @mbg.generated Mon May 07 13:22:50 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.PASSWORD
     *
     * @return the value of admin.PASSWORD
     *
     * @mbg.generated Mon May 07 13:22:50 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.PASSWORD
     *
     * @param password the value for admin.PASSWORD
     *
     * @mbg.generated Mon May 07 13:22:50 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }
}