package com.exam.ssm.model;

public class Gradeclass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gradeclass.classid
     *
     * @mbg.generated Thu May 10 12:33:35 CST 2018
     */
    private Integer classid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gradeclass.grade
     *
     * @mbg.generated Thu May 10 12:33:35 CST 2018
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gradeclass.classnum
     *
     * @mbg.generated Thu May 10 12:33:35 CST 2018
     */
    private String classnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gradeclass.major
     *
     * @mbg.generated Thu May 10 12:33:35 CST 2018
     */
    private String major;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gradeclass.classid
     *
     * @return the value of gradeclass.classid
     *
     * @mbg.generated Thu May 10 12:33:35 CST 2018
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gradeclass.classid
     *
     * @param classid the value for gradeclass.classid
     *
     * @mbg.generated Thu May 10 12:33:35 CST 2018
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gradeclass.grade
     *
     * @return the value of gradeclass.grade
     *
     * @mbg.generated Thu May 10 12:33:35 CST 2018
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gradeclass.grade
     *
     * @param grade the value for gradeclass.grade
     *
     * @mbg.generated Thu May 10 12:33:35 CST 2018
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gradeclass.classnum
     *
     * @return the value of gradeclass.classnum
     *
     * @mbg.generated Thu May 10 12:33:35 CST 2018
     */
    public String getClassnum() {
        return classnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gradeclass.classnum
     *
     * @param classnum the value for gradeclass.classnum
     *
     * @mbg.generated Thu May 10 12:33:35 CST 2018
     */
    public void setClassnum(String classnum) {
        this.classnum = classnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gradeclass.major
     *
     * @return the value of gradeclass.major
     *
     * @mbg.generated Thu May 10 12:33:35 CST 2018
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gradeclass.major
     *
     * @param major the value for gradeclass.major
     *
     * @mbg.generated Thu May 10 12:33:35 CST 2018
     */
    public void setMajor(String major) {
        this.major = major;
    }
}