package com.exam.ssm.model;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messageid
     *
     * @mbg.generated Tue May 08 11:37:39 CST 2018
     */
    private Integer messageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messagetype
     *
     * @mbg.generated Tue May 08 11:37:39 CST 2018
     */
    private String messagetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messagetitle
     *
     * @mbg.generated Tue May 08 11:37:39 CST 2018
     */
    private String messagetitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messagetarget
     *
     * @mbg.generated Tue May 08 11:37:39 CST 2018
     */
    private Integer messagetarget;

    @Override
    public String toString() {
        return "Message{" +
                "messageid=" + messageid +
                ", messagetype='" + messagetype + '\'' +
                ", messagetitle='" + messagetitle + '\'' +
                ", messagetarget=" + messagetarget +
                ", messagetime=" + messagetime +
                ", messagecontent='" + messagecontent + '\'' +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messagetime
     *
     * @mbg.generated Tue May 08 11:37:39 CST 2018
     */
    private Date messagetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messagecontent
     *
     * @mbg.generated Tue May 08 11:37:39 CST 2018
     */
    private String messagecontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messageid
     *
     * @return the value of message.messageid
     *
     * @mbg.generated Tue May 08 11:37:39 CST 2018
     */
    public Integer getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messageid
     *
     * @param messageid the value for message.messageid
     *
     * @mbg.generated Tue May 08 11:37:39 CST 2018
     */
    public void setMessageid(Integer messageid) {
        this.messageid = messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messagetype
     *
     * @return the value of message.messagetype
     *
     * @mbg.generated Tue May 08 11:37:39 CST 2018
     */
    public String getMessagetype() {
        return messagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messagetype
     *
     * @param messagetype the value for message.messagetype
     *
     * @mbg.generated Tue May 08 11:37:39 CST 2018
     */
    public void setMessagetype(String messagetype) {
        this.messagetype = messagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messagetitle
     *
     * @return the value of message.messagetitle
     *
     * @mbg.generated Tue May 08 11:37:39 CST 2018
     */
    public String getMessagetitle() {
        return messagetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messagetitle
     *
     * @param messagetitle the value for message.messagetitle
     *
     * @mbg.generated Tue May 08 11:37:39 CST 2018
     */
    public void setMessagetitle(String messagetitle) {
        this.messagetitle = messagetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messagetarget
     *
     * @return the value of message.messagetarget
     *
     * @mbg.generated Tue May 08 11:37:39 CST 2018
     */
    public Integer getMessagetarget() {
        return messagetarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messagetarget
     *
     * @param messagetarget the value for message.messagetarget
     *
     * @mbg.generated Tue May 08 11:37:39 CST 2018
     */
    public void setMessagetarget(Integer messagetarget) {
        this.messagetarget = messagetarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messagetime
     *
     * @return the value of message.messagetime
     *
     * @mbg.generated Tue May 08 11:37:39 CST 2018
     */
    public Date getMessagetime() {
        return messagetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messagetime
     *
     * @param messagetime the value for message.messagetime
     *
     * @mbg.generated Tue May 08 11:37:39 CST 2018
     */
    public void setMessagetime(Date messagetime) {
        this.messagetime = messagetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messagecontent
     *
     * @return the value of message.messagecontent
     *
     * @mbg.generated Tue May 08 11:37:39 CST 2018
     */
    public String getMessagecontent() {
        return messagecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messagecontent
     *
     * @param messagecontent the value for message.messagecontent
     *
     * @mbg.generated Tue May 08 11:37:39 CST 2018
     */
    public void setMessagecontent(String messagecontent) {
        this.messagecontent = messagecontent;
    }
}