package com.exam.ssm.model;

public class Studentscourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentscourse.id
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentscourse.SID
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentscourse.courseid
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    private String courseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentscourse.coursename
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    private String coursename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentscourse.times
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    private String times;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentscourse.weeks
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    private String weeks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentscourse.nodes
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    private String nodes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentscourse.classlocationnum
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    private String classlocationnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentscourse.tid
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentscourse.id
     *
     * @return the value of studentscourse.id
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentscourse.id
     *
     * @param id the value for studentscourse.id
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentscourse.SID
     *
     * @return the value of studentscourse.SID
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentscourse.SID
     *
     * @param sid the value for studentscourse.SID
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentscourse.courseid
     *
     * @return the value of studentscourse.courseid
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    public String getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentscourse.courseid
     *
     * @param courseid the value for studentscourse.courseid
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    public void setCourseid(String courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentscourse.coursename
     *
     * @return the value of studentscourse.coursename
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentscourse.coursename
     *
     * @param coursename the value for studentscourse.coursename
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentscourse.times
     *
     * @return the value of studentscourse.times
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    public String getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentscourse.times
     *
     * @param times the value for studentscourse.times
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    public void setTimes(String times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentscourse.weeks
     *
     * @return the value of studentscourse.weeks
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    public String getWeeks() {
        return weeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentscourse.weeks
     *
     * @param weeks the value for studentscourse.weeks
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    public void setWeeks(String weeks) {
        this.weeks = weeks;
    }


    public String getNodes() {
        return nodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentscourse.nodes
     *
     * @param nodes the value for studentscourse.nodes
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    public void setNodes(String nodes) {
        this.nodes = nodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentscourse.classlocationnum
     *
     * @return the value of studentscourse.classlocationnum
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    public String getClasslocationnum() {
        return classlocationnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentscourse.classlocationnum
     *
     * @param classlocationnum the value for studentscourse.classlocationnum
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    public void setClasslocationnum(String classlocationnum) {
        this.classlocationnum = classlocationnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentscourse.tid
     *
     * @return the value of studentscourse.tid
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentscourse.tid
     *
     * @param tid the value for studentscourse.tid
     *
     * @mbg.generated Wed May 09 14:01:26 CST 2018
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}