package com.exam.ssm.model;

public class Teacherscourse {

    private Integer id;


    private Integer tid;


    private String courseid;


    private String coursename;


    private String times;


    private String weeks;


    private String nodes;


    private String classlocationnum;


    private String classid;


    public Integer getId() {
        return id;
    }


    public void setId(Integer id) {
        this.id = id;
    }


    public Integer getTid() {
        return tid;
    }


    public void setTid(Integer tid) {
        this.tid = tid;
    }


    public String getCourseid() {
        return courseid;
    }


    public void setCourseid(String courseid) {
        this.courseid = courseid;
    }


    public String getCoursename() {
        return coursename;
    }


    public void setCoursename(String coursename) {
        this.coursename = coursename;
    }


    public String getTimes() {
        return times;
    }


    public void setTimes(String times) {
        this.times = times;
    }


    public String getWeeks() {
        return weeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacherscourse.weeks
     *
     * @param weeks the value for teacherscourse.weeks
     *
     * @mbg.generated Thu May 10 11:07:17 CST 2018
     */
    public void setWeeks(String weeks) {
        this.weeks = weeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacherscourse.nodes
     *
     * @return the value of teacherscourse.nodes
     *
     * @mbg.generated Thu May 10 11:07:17 CST 2018
     */
    public String getNodes() {
        return nodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacherscourse.nodes
     *
     * @param nodes the value for teacherscourse.nodes
     *
     * @mbg.generated Thu May 10 11:07:17 CST 2018
     */
    public void setNodes(String nodes) {
        this.nodes = nodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacherscourse.classlocationnum
     *
     * @return the value of teacherscourse.classlocationnum
     *
     * @mbg.generated Thu May 10 11:07:17 CST 2018
     */
    public String getClasslocationnum() {
        return classlocationnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacherscourse.classlocationnum
     *
     * @param classlocationnum the value for teacherscourse.classlocationnum
     *
     * @mbg.generated Thu May 10 11:07:17 CST 2018
     */
    public void setClasslocationnum(String classlocationnum) {
        this.classlocationnum = classlocationnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacherscourse.classid
     *
     * @return the value of teacherscourse.classid
     *
     * @mbg.generated Thu May 10 11:07:17 CST 2018
     */
    public String getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacherscourse.classid
     *
     * @param classid the value for teacherscourse.classid
     *
     * @mbg.generated Thu May 10 11:07:17 CST 2018
     */
    public void setClassid(String classid) {
        this.classid = classid;
    }
}